illia-rudniev/fix/production-logs-format-fix
ballerine-io/ballerine pull request #1569
Opened 2023-11-06 11:32 UTC by chesterkmr

### Description
 - fixed bug where logs in production were outputted with colorization codes
 - removed reduntant logger initialization in main.ts

### Related issues
 * Provide a link to each related issue.

### Breaking changes
 * Describe the breaking changes that this pull request introduces.

### How these changes were tested
 * Describe the tests that you ran to verify your changes, including devices, operating systems, browsers and versions.

### Examples and references
 * Links, screenshots, and other resources related to this change.

### Checklist
- [] I have read the [contribution guidelines](CONTRIBUTING.md) of this project
- [] I have read the [style guidelines](STYLE_GUIDE.md) of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings and errors
- [] New and existing tests pass locally with my changes

2023-11-06 12:46 UTC, liorzblrn requested changes

2023-11-06 12:46 UTC, liorzblrn commented on services/workflows-service/src/main.ts
> -import cookieSession from 'cookie-session';
please revert changes in this file, will be changed in my another PR
https://github.com/ballerine-io/ballerine/pull/1568/files#diff-d53b043ddda2125d7ae915af1d7b718a8800e1d48d28034fd347b093c67bf5ea
![Uploading image.png…]()

2023-11-06 12:55 UTC, liorzblrn requested changes

2023-11-06 12:55 UTC, liorzblrn commented on services/workflows-service/src/main.ts
> -  app.useLogger(logger);
please revert this line

2023-11-07 08:53 UTC, liorzam commented
Fixed on: https://github.com/ballerine-io/ballerine/pull/1568

2023-11-07 08:53 UTC, closed without merging